services:
  app:
    build: .
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "80:80"
      - "443:443"
      - "5173:5173"
    volumes:
      - ./:/var/www/html
      - ~/.composer:/root/.composer
      - ~/.npm:/root/.npm
      - ~/.local/share/pnpm:/root/.local/share/pnpm
    environment:
      - DOCUMENT_ROOT=/var/www/html/public
      - PUID=1000
      - PGID=1000
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4.5
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql

volumes:
  mysql_data: